name: Deploy Python Predictor

on:
  push:
    branches: [ main ]

env:
  DOCKER_IMAGE: resource-predictor
  SERVICE_NAME: resource-predictor

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build & Push Docker Image
      run: |
        IMAGE_TAG=${{ github.sha }}
        docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE }}:$IMAGE_TAG .
        docker push ${{ secrets.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE }}:$IMAGE_TAG
        echo "PREDICTOR_IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Deploy via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        port: 8822
        key: ${{ secrets.PRIVATE_KEY }}
        script: |
          cd ~/docker/javame
          
          if grep -q '^PREDICTOR_IMAGE_TAG=' .env; then
            sed -i "s|^PREDICTOR_IMAGE_TAG=.*|PREDICTOR_IMAGE_TAG=${{ github.sha }}|" .env
          else
            echo "PREDICTOR_IMAGE_TAG=${{ github.sha }}" >> .env
          fi
          
          docker-compose pull resource-predictor
          docker-compose up -d resource-predictor
